import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./context/SessionProvider";
import ToasterContext from "./context/ToasterContext";
import { getServerSession } from "next-auth";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { logDbConnections } from "@/utils/logDbConnections";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  logDbConnections();
  return (
    <html lang="en">
      <Provider session={session}>
        <body className={inter.className}>
          <ToasterContext />
          <Navbar />
          {children}
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
